CFLAGS=/nologo /DINLINE=
LINK=link

!ifdef BUILD_OPT
CFLAGS=$(CFLAGS) /O1
LFLAGS=
!else
CFLAGS=$(CFLAGS) /Zi /Od
LFLAGS=/debug
!endif


OBJS=rete-test.obj pool.obj rete.obj wmem.obj

rete-test.exe: $(OBJS)
        $(LINK) $(LFLAGS) /out:$@ $(OBJS)

rete-test.obj: rete-test.c
pool.obj: pool.c
rete.obj: rete.c
wmem.obj: wmem.c

clean:
        del *.obj *.exe *.pdb *.ilk *~

